open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F
  open Types

  let reserved = ptr void

  let tag = ptr void

  let grpc_init = foreign "grpc_init" (void @-> returning void)

  let grpc_shutdown = foreign "grpc_shutdown" (void @-> returning void)

  let grpc_version_string =
    foreign "grpc_version_string" (void @-> returning string)

  let grpc_g_stands_for = foreign "grpc_g_stands_for" (void @-> returning string)

  let grpc_server_create =
    foreign "grpc_server_create"
      (ptr_opt grpc_channel_args @-> reserved @-> returning (ptr grpc_server))

  let grpc_server_shutdown_and_notify =
    foreign "grpc_server_shutdown_and_notify"
      (ptr grpc_server @-> ptr grpc_completion_queue @-> tag @-> returning void)

  let grpc_server_destroy =
    foreign "grpc_server_destroy" (ptr grpc_server @-> returning void)

  let grpc_server_cancel_all_calls =
    foreign "grpc_server_cancel_all_calls" (ptr grpc_server @-> returning void)

  let grpc_completion_queue_create_for_next =
    foreign "grpc_completion_queue_create_for_next"
      (reserved @-> returning (ptr grpc_completion_queue))

  let grpc_completion_queue_create_for_pluck =
    foreign "grpc_completion_queue_create_for_pluck"
      (reserved @-> returning (ptr grpc_completion_queue))

  let grpc_completion_queue_shutdown =
    foreign "grpc_completion_queue_shutdown"
      (ptr grpc_completion_queue @-> returning void)

  let grpc_completion_queue_destroy =
    foreign "grpc_completion_queue_destroy"
      (ptr grpc_completion_queue @-> returning void)

  let grpc_completion_queue_next =
    foreign "grpc_completion_queue_next"
      (ptr grpc_completion_queue @-> GPR_timespec.t @-> reserved
     @-> returning GRPC_event.t)

  let grpc_completion_queue_pluck =
    foreign "grpc_completion_queue_pluck"
      (ptr grpc_completion_queue @-> tag @-> GPR_timespec.t @-> reserved
     @-> returning GRPC_event.t)

  let grpc_server_register_completion_queue =
    foreign "grpc_server_register_completion_queue"
      (ptr grpc_server @-> ptr grpc_completion_queue @-> reserved
     @-> returning void)

  let grpc_server_add_insecure_http2_port =
    foreign "grpc_server_add_insecure_http2_port"
      (ptr grpc_server @-> string @-> returning int)

  let grpc_server_start =
    foreign "grpc_server_start" (ptr grpc_server @-> returning void)

  let grpc_slice_length =
    foreign "GRPC_SLICE_LENGTH" (GRPC_slice.t @-> returning size_t)

  let grpc_slice_from_copied_buffer =
    foreign "grpc_slice_from_copied_buffer"
      (ocaml_string @-> size_t @-> returning GRPC_slice.t)

  let grpc_server_request_call =
    foreign "grpc_server_request_call"
      (ptr grpc_server
      @-> ptr (ptr grpc_call)
      @-> ptr GRPC_call_details.t @-> ptr GRPC_metadata_array.t
      @-> ptr grpc_completion_queue @-> ptr grpc_completion_queue @-> ptr void
      @-> returning GRPC_call_error.t)

  let grpc_call_error_to_string =
    foreign "grpc_call_error_to_string" (GRPC_call_error.t @-> returning string)
end
