(lang dune 3.0)

(authors "François Bobot")
(maintainers "François Bobot")
(source (github bobot/fabric-chaincode-ocaml))

(package
 (name fabric-chaincode-ocaml-test)
 (depends fabric-chaincode-shim)
)
