open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F
  open Types

  let reserved = ptr void
  let tag = ptr void
  let grpc_init = foreign "grpc_init" (void @-> returning void)
  let grpc_shutdown = foreign "grpc_shutdown" (void @-> returning void)

  let grpc_version_string =
    foreign "grpc_version_string" (void @-> returning string)

  let grpc_g_stands_for = foreign "grpc_g_stands_for" (void @-> returning string)

  let grpc_server_create =
    foreign "grpc_server_create"
      (ptr_opt grpc_channel_args @-> reserved @-> returning (ptr grpc_server))

  let grpc_server_shutdown_and_notify =
    foreign "grpc_server_shutdown_and_notify"
      (ptr grpc_server @-> ptr grpc_completion_queue @-> tag @-> returning void)

  let grpc_server_destroy =
    foreign "grpc_server_destroy" (ptr grpc_server @-> returning void)

  let grpc_server_cancel_all_calls =
    foreign "grpc_server_cancel_all_calls" (ptr grpc_server @-> returning void)

  let grpc_completion_queue_create_for_next =
    foreign "grpc_completion_queue_create_for_next"
      (reserved @-> returning (ptr grpc_completion_queue))

  let grpc_completion_queue_create_for_pluck =
    foreign "grpc_completion_queue_create_for_pluck"
      (reserved @-> returning (ptr grpc_completion_queue))

  let grpc_completion_queue_shutdown =
    foreign "grpc_completion_queue_shutdown"
      (ptr grpc_completion_queue @-> returning void)

  let grpc_completion_queue_destroy =
    foreign "grpc_completion_queue_destroy"
      (ptr grpc_completion_queue @-> returning void)

  let grpc_completion_queue_next =
    foreign "grpc_completion_queue_next"
      (ptr grpc_completion_queue @-> GPR_timespec.t @-> reserved
     @-> returning GRPC_event.t)

  let grpc_completion_queue_pluck =
    foreign "grpc_completion_queue_pluck"
      (ptr grpc_completion_queue @-> tag @-> GPR_timespec.t @-> reserved
     @-> returning GRPC_event.t)

  let grpc_server_register_completion_queue =
    foreign "grpc_server_register_completion_queue"
      (ptr grpc_server @-> ptr grpc_completion_queue @-> reserved
     @-> returning void)

  let grpc_server_add_insecure_http2_port =
    foreign "grpc_server_add_insecure_http2_port"
      (ptr grpc_server @-> string @-> returning int)

  let grpc_server_start =
    foreign "grpc_server_start" (ptr grpc_server @-> returning void)

  let grpc_slice_length =
    foreign "GRPC_SLICE_LENGTH" (GRPC_slice.t @-> returning size_t)

  let grpc_slice_from_copied_buffer =
    foreign "grpc_slice_from_copied_buffer"
      (ocaml_string @-> size_t @-> returning GRPC_slice.t)

  let grpc_server_request_call =
    foreign "grpc_server_request_call"
    @@ ptr grpc_server
    @-> ptr (ptr grpc_call)
    @-> ptr GRPC_call_details.t @-> ptr GRPC_metadata_array.t
    @-> ptr grpc_completion_queue @-> ptr grpc_completion_queue @-> ptr void
    @-> returning GRPC_call_error.t

  let grpc_call_error_to_string =
    foreign "grpc_call_error_to_string" (GRPC_call_error.t @-> returning string)

  let grpc_insecure_channel_create =
    foreign "grpc_insecure_channel_create"
    @@ string @-> ptr_opt grpc_channel_args @-> reserved
    @-> returning (ptr grpc_channel)

  let grpc_channel_check_connectivity_state =
    foreign "grpc_channel_check_connectivity_state"
    @@ ptr grpc_channel @-> bool
    @-> returning GRPC_connectivity_state.t

  let grpc_channel_destroy =
    foreign "grpc_channel_destroy" @@ ptr grpc_channel @-> returning void

  let grpc_channel_create_call =
    foreign "grpc_channel_create_call"
    @@ ptr grpc_channel @-> ptr_opt grpc_call @-> uint32_t
    @-> ptr grpc_completion_queue @-> GRPC_slice.t @-> ptr_opt GRPC_slice.t
    @-> GPR_timespec.t @-> reserved
    @-> returning (ptr grpc_call)

  let grpc_call_start_batch =
    foreign "grpc_call_start_batch"
    @@ ptr grpc_call @-> ptr GRPC_op.t @-> size_t @-> tag @-> reserved
    @-> returning GRPC_call_error.t

  let grpc_slice_unref =
    foreign "grpc_slice_unref" @@ GRPC_slice.t @-> returning void

  let grpc_call_unref =
    foreign "grpc_call_unref" @@ ptr grpc_call @-> returning void

  let grpc_slice_buffer_init =
    foreign "grpc_slice_buffer_init"
    @@ ptr GRPC_slice_buffer.t @-> returning void

  let grpc_slice_buffer_destroy =
    foreign "grpc_slice_buffer_destroy"
    @@ ptr GRPC_slice_buffer.t @-> returning void

  let grpc_metadata_array_init =
    foreign "grpc_metadata_array_init"
    @@ ptr GRPC_metadata_array.t @-> returning void

  let grpc_metadata_array_destroy =
    foreign "grpc_metadata_array_destroy"
    @@ ptr GRPC_metadata_array.t @-> returning void

  let grpc_call_details_init =
    foreign "grpc_call_details_init"
    @@ ptr GRPC_call_details.t @-> returning void

  let grpc_call_details_destroy =
    foreign "grpc_call_details_destroy"
    @@ ptr GRPC_call_details.t @-> returning void

  let grpc_slice_buffer_add =
    foreign "grpc_slice_buffer_add"
    @@ ptr GRPC_slice_buffer.t @-> GRPC_slice.t @-> returning void

  let grpc_byte_buffer_destroy =
    foreign "grpc_byte_buffer_destroy"
    @@ ptr GRPC_byte_buffer.t @-> returning void

  let gpr_free = foreign "gpr_free" @@ ptr void @-> returning void

  let grpc_empty_slice =
    foreign "grpc_empty_slice" @@ void @-> returning GRPC_slice.t
end
